# Config definition
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 1.Data General Setting. Can be replaced in respective sets
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
DATA:
 DATASETS:
  NAMES: ('general-sequence')
  ROOT_DIR: ('./data')

 DATALOADER:
  NUM_WORKERS: 0
  SAMPLER: 'random' #'class_balance_random'

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 2.Model General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
MODEL:
 DEVICE: "cuda"
 DEVICE_ID: (0,)
 BACKBONE_NAME: "esm1b"
 CONTACT_PREDICTOR_NAME: "contact-predictor"
 BIAS_FREE: 0

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 3.LOSS General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
LOSS:
 TYPE: 'contact_prediction_loss'

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 4.Solver
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
SOLVER:
 MAX_EPOCHS: 30
 EVAL_PERIOD: 1
 CHECKPOINT_PERIOD: 1
 LOG_PERIOD: 1
 OUTPUT_DIR: "work_space" 

 # OPTIMIZER
 OPTIMIZER:
  NAME: "Adam"                         #"SGD", "Adam"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  ACCUMULATION_STEP: 1

 # SCHEDULER
 SCHEDULER:
  BASE_LR: 0.0001       
  BIAS_LR_FACTOR: 1
  GAMMA: 0.1
  STEPS: [8, 12, 16, 20]                #[10, 15, 20, 25]
  WARMUP_FACTOR: 0.33
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
  LOSS_LR: 0.05
  RETRAIN_FROM_HEAD: 1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Train Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TRAIN:
 WEIGHT: ""
 DATALOADER:
  CATEGORIES_PER_BATCH: 10
  INSTANCES_PER_CATEGORY_IN_BATCH: 6

 # Train Trick
 TRICK:
  PRETRAIN_PATH: './pretrained/esm1b_t33_650M_UR50S.pt'
  PRETRAINED: 1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Val Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
VAL:
 WEIGHT: "" 
 DATALOADER:
  CATEGORIES_PER_BATCH: 10
  INSTANCES_PER_CATEGORY_IN_BATCH: 6

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Test Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TEST:
 WEIGHT: "./work_space/densenet121_model_20.pth" 
 DATALOADER:
  CATEGORIES_PER_BATCH: 10
  INSTANCES_PER_CATEGORY_IN_BATCH: 6